### ISSUE TITLE
 'Model' object has no attribute 'yaml'

### ISSUE THREAD

**Issue by hopesala** [hukaixuan19970627/YOLOv5_DOTA_OBB#84]
Traceback (most recent call last):
  File "train.py", line 727, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 127, in train
    model = Model(opt.cfg or ckpt['model'].yaml, ch=3, nc=nc).to(device)  # create
  File "/home/cao/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Model' object has no attribute 'yaml'

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/133392548-eb7ce6e8-d05b-45cb-bf7c-f0bda058a7a0.png)
Maybe the version of pytorch is the reason.
